---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible_role_git_credential_manager_opensuse
    image: opensuse:42.2

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: opensuse

verifier:
  name: testinfra
  lint:
    name: flake8
