# code: language=ansible
---
- name: Create download directory
  ansible.builtin.file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: '{{ git_credential_manager_download_dir }}'

- name: Download the Git Credential Manager
  ansible.builtin.get_url:
    url: '{{ git_credential_manager_mirror }}/{{ git_credential_manager_redis_filename }}'
    dest: '{{ git_credential_manager_download_dir }}/{{ git_credential_manager_redis_filename }}'
    checksum: 'sha256:{{ git_credential_manager_redis_sha256sum }}'
    force: false
    use_proxy: true
    validate_certs: true
    mode: 'u=rw,go=r'

- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name:
      - git
      - icu-devtools
      - libsecret-1-0
    state: present

- name: Install Git Credential Manager
  become: true
  ansible.builtin.apt:
    deb: '{{ git_credential_manager_download_dir }}/{{ git_credential_manager_redis_filename }}'

- name: Configure Git (credential helper)
  become: true
  ansible.builtin.git_config:
    scope: system
    name: 'credential.helper'
    value: '{{ git_credential_manager_credential_helper }}'

- name: Configure Git (credential store)
  become: true
  ansible.builtin.git_config:
    scope: system
    name: 'credential.credentialStore'
    value: '{{ git_credential_manager_credential_store }}'
