---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible_role_git_credential_manager_centos
    image: centos:7

provisioner:
  name: ansible
  playbooks:
    converge: ../default/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: centos

verifier:
  name: testinfra
  lint:
    name: flake8
