# code: language=ansible
---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  roles:
    - role: ansible_role_git_credential_manager
