---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_git_credential_manager_debian_min
    image: debian:10

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: debian_min

verifier:
  name: testinfra
  directory: ../default/tests/
